In [1]:
import numpy as np
import pandas as pd

np.random.seed(42)

target_count = 2000

suitable_data = []
unsuitable_data = []

while len(suitable_data) < target_count or len(unsuitable_data) < target_count:

    pH = np.random.uniform(6.0, 8.5)
    nitrate = np.random.uniform(0, 100)  # ppm
    sulfate = np.random.uniform(0, 250)  # ppm
    tds = np.random.uniform(0, 3000)  # ppm
    bacterial_count = np.random.randint(0, 1000)  # CFU/mL
    hardness = np.random.uniform(0, 500)  # mg/L
    temperature = np.random.uniform(15, 25)  # Â°C

    if (
        6.0 <= pH <= 8.5 and
        nitrate <= 44 and
        sulfate <= 250 and
        tds <= 3000 and
        bacterial_count <= 500 and
        hardness <= 500 and
        15 <= temperature <= 25
    ):

        if len(suitable_data) < target_count:
            suitable_data.append([pH, nitrate, sulfate, tds, bacterial_count, hardness, temperature, "Suitable"])
    else:

        if len(unsuitable_data) < target_count:
            unsuitable_data.append([pH, nitrate, sulfate, tds, bacterial_count, hardness, temperature, "Unsuitable"])

balanced_data = suitable_data + unsuitable_data

balanced_water_quality_data = pd.DataFrame(balanced_data, columns=[
    'pH', 'Nitrate', 'Sulfate', 'Total_Dissolved_Solids', 'Bacterial_Count', 'Hardness', 'Temperature', 'Suitability'
])


print("Balanced Target Variable Distribution:")
print(balanced_water_quality_data['Suitability'].value_counts())


balanced_water_quality_data.to_csv('balanced_water_quality_data_cowsv2.csv', index=False)

Balanced Target Variable Distribution:
Suitable      2000
Unsuitable    2000
Name: Suitability, dtype: int64

In [9]:
balanced_water_quality_data.head()

,pH,Nitrate,Sulfate,Total_Dissolved_Solids,Bacterial_Count,Hardness,Temperature,Suitability
0,7.148122,33.370861,35.716704,1952.665419,308,484.954926,23.324426,Suitable
1,6.530848,18.182497,45.851127,912.726729,21,3.533153,15.230624,Suitable
2,7.100381,12.203823,123.794228,103.165563,205,195.530304,16.822361,Suitable
3,7.888404,42.515587,51.985416,1703.100983,476,484.792314,22.751328,Suitable
4,6.733720,1.407982,49.710601,2134.025858,418,385.635173,15.740447,Suitable